### ISSUE TITLE
Stjopa's bug

### ISSUE THREAD

**Issue by albert-tarly** [besuhoff/spender-js#37]
```
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`spender`.`expense`, CONSTRAINT `expense_fk_904832` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`))' in /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php:57 Stack trace: #0 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php(57): PDOStatement->execute(NULL) #1 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/StatementWrapper.php(194): Propel\Runtime\Adapter\Pdo\PdoStatement->execute(NULL) #2 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php(2610): Propel\Runtime\Connection\StatementWrapper->execute() #3 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1512): Propel\Runtime\ActiveQuery\Criteria->doDelete(Object(Propel\Runtime\Connection\ConnectionWrapper)) #4 [internal function]: Propel\Runtime\ActiveQuery\ModelCriteria->Propel\Runtime\ActiveQuery\{closure}() #5 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure)) #6 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1517): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure)) #7 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/CategoryQuery.php(747): Propel\Runtime\ActiveQuery\ModelCriteria->delete(Object(Propel\Runtime\Connection\ConnectionWrapper)) #8 [internal function]: Base\CategoryQuery->Base\{closure}() #9 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure)) #10 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/CategoryQuery.php(751): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure)) #11 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/Category.php(743): Base\CategoryQuery->delete(Object(Propel\Runtime\Connection\ConnectionWrapper)) #12 [internal function]: Base\Category->Base\{closure}() #13 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure)) #14 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/Category.php(747): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure)) #15 /home/besuhoff/project/spender-backend/html/index.php(174): Base\Category->delete() #16 [internal function]: Closure->{closure}(Object(Bullet\Request)) #17 /home/besuhoff/project/spender-backend/vendor/vlucas/bulletphp/src/Bullet/App.php(311): call_user_func(Object(Closure), Object(Bullet\Request)) #18 /home/besuhoff/project/spender-backend/vendor/vlucas/bulletphp/src/Bullet/App.php(195): Bullet\App->_runPath('DELETE', '30') #19 /home/besuhoff/project/spender-backend/html/index.php(339): Bullet\App->run(Object(Bullet\Request)) #20 {main} Next exception 'Propel\Runtime\Exception\PropelException' with message 'Unable to execute DELETE statement [DELETE FROM category WHERE category.id=:p1]' in /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php:2614 Stack trace: #0 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1512): Propel\Runtime\ActiveQuery\Criteria->doDelete(Object(Propel\Runtime\Connection\ConnectionWrapper)) #1 [internal function]: Propel\Runtime\ActiveQuery\ModelCriteria->Propel\Runtime\ActiveQuery\{closure}() #2 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure)) #3 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1517): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure)) #4 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/CategoryQuery.php(747): Propel\Runtime\ActiveQuery\ModelCriteria->delete(Object(Propel\Runtime\Connection\ConnectionWrapper)) #5 [internal function]: Base\CategoryQuery->Base\{closure}() #6 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure)) #7 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/CategoryQuery.php(751): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure)) #8 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/Category.php(743): Base\CategoryQuery->delete(Object(Propel\Runtime\Connection\ConnectionWrapper)) #9 [internal function]: Base\Category->Base\{closure}() #10 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure)) #11 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/Category.php(747): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure)) #12 /home/besuhoff/project/spender-backend/html/index.php(174): Base\Category->delete() #13 [internal function]: Closure->{closure}(Object(Bullet\Request)) #14 /home/besuhoff/project/spender-backend/vendor/vlucas/bulletphp/src/Bullet/App.php(311): call_user_func(Object(Closure), Object(Bullet\Request)) #15 /home/besuhoff/project/spender-backend/vendor/vlucas/bulletphp/src/Bullet/App.php(195): Bullet\App->_runPath('DELETE', '30') #16 /home/besuhoff/project/spender-backend/html/index.php(339): Bullet\App->run(Object(Bullet\Request)) #17 {main} Next exception 'Propel\Runtime\Exception\PropelException' with message 'Propel\Runtime\ActiveQuery\ModelCriteria::delete is unable to delete. ' in /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php:1519 Stack trace: #0 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/CategoryQuery.php(747): Propel\Runtime\ActiveQuery\ModelCriteria->delete(Object(Propel\Runtime\Connection\ConnectionWrapper)) #1 [internal function]: Base\CategoryQuery->Base\{closure}() #2 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure)) #3 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/CategoryQuery.php(751): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure)) #4 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/Category.php(743): Base\CategoryQuery->delete(Object(Propel\Runtime\Connection\ConnectionWrapper)) #5 [internal function]: Base\Category->Base\{closure}() #6 /home/besuhoff/project/spender-backend/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure)) #7 /home/besuhoff/project/spender-backend/spender/generated-classes/Base/Category.php(747): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure)) #8 /home/besuhoff/project/spender-backend/html/index.php(174): Base\Category->delete() #9 [internal function]: Closure->{closure}(Object(Bullet\Request)) #10 /home/besuhoff/project/spender-backend/vendor/vlucas/bulletphp/src/Bullet/App.php(311): call_user_func(Object(Closure), Object(Bullet\Request)) #11 /home/besuhoff/project/spender-backend/vendor/vlucas/bulletphp/src/Bullet/App.php(195): Bullet\App->_runPath('DELETE', '30') #12 /home/besuhoff/project/spender-backend/html/index.php(339): Bullet\App->run(Object(Bullet\Request)) #13 {main}
```

**Comment by albert-tarly** [comment]
Not sure if it still exists
